/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  SecurityCheck as PrismaSecurityCheck,
  Flight as PrismaFlight,
  Passenger as PrismaPassenger,
} from "@prisma/client";

export class SecurityCheckServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SecurityCheckCountArgs, "select">
  ): Promise<number> {
    return this.prisma.securityCheck.count(args);
  }

  async securityChecks(
    args: Prisma.SecurityCheckFindManyArgs
  ): Promise<PrismaSecurityCheck[]> {
    return this.prisma.securityCheck.findMany(args);
  }
  async securityCheck(
    args: Prisma.SecurityCheckFindUniqueArgs
  ): Promise<PrismaSecurityCheck | null> {
    return this.prisma.securityCheck.findUnique(args);
  }
  async createSecurityCheck(
    args: Prisma.SecurityCheckCreateArgs
  ): Promise<PrismaSecurityCheck> {
    return this.prisma.securityCheck.create(args);
  }
  async updateSecurityCheck(
    args: Prisma.SecurityCheckUpdateArgs
  ): Promise<PrismaSecurityCheck> {
    return this.prisma.securityCheck.update(args);
  }
  async deleteSecurityCheck(
    args: Prisma.SecurityCheckDeleteArgs
  ): Promise<PrismaSecurityCheck> {
    return this.prisma.securityCheck.delete(args);
  }

  async getFlight(parentId: string): Promise<PrismaFlight | null> {
    return this.prisma.securityCheck
      .findUnique({
        where: { id: parentId },
      })
      .flight();
  }

  async getPassenger(parentId: string): Promise<PrismaPassenger | null> {
    return this.prisma.securityCheck
      .findUnique({
        where: { id: parentId },
      })
      .passenger();
  }
}
