/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SecurityCheck } from "./SecurityCheck";
import { SecurityCheckCountArgs } from "./SecurityCheckCountArgs";
import { SecurityCheckFindManyArgs } from "./SecurityCheckFindManyArgs";
import { SecurityCheckFindUniqueArgs } from "./SecurityCheckFindUniqueArgs";
import { CreateSecurityCheckArgs } from "./CreateSecurityCheckArgs";
import { UpdateSecurityCheckArgs } from "./UpdateSecurityCheckArgs";
import { DeleteSecurityCheckArgs } from "./DeleteSecurityCheckArgs";
import { Flight } from "../../flight/base/Flight";
import { Passenger } from "../../passenger/base/Passenger";
import { SecurityCheckService } from "../securityCheck.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SecurityCheck)
export class SecurityCheckResolverBase {
  constructor(
    protected readonly service: SecurityCheckService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "any",
  })
  async _securityChecksMeta(
    @graphql.Args() args: SecurityCheckCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SecurityCheck])
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "any",
  })
  async securityChecks(
    @graphql.Args() args: SecurityCheckFindManyArgs
  ): Promise<SecurityCheck[]> {
    return this.service.securityChecks(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SecurityCheck, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "own",
  })
  async securityCheck(
    @graphql.Args() args: SecurityCheckFindUniqueArgs
  ): Promise<SecurityCheck | null> {
    const result = await this.service.securityCheck(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SecurityCheck)
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "create",
    possession: "any",
  })
  async createSecurityCheck(
    @graphql.Args() args: CreateSecurityCheckArgs
  ): Promise<SecurityCheck> {
    return await this.service.createSecurityCheck({
      ...args,
      data: {
        ...args.data,

        flight: args.data.flight
          ? {
              connect: args.data.flight,
            }
          : undefined,

        passenger: args.data.passenger
          ? {
              connect: args.data.passenger,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SecurityCheck)
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "update",
    possession: "any",
  })
  async updateSecurityCheck(
    @graphql.Args() args: UpdateSecurityCheckArgs
  ): Promise<SecurityCheck | null> {
    try {
      return await this.service.updateSecurityCheck({
        ...args,
        data: {
          ...args.data,

          flight: args.data.flight
            ? {
                connect: args.data.flight,
              }
            : undefined,

          passenger: args.data.passenger
            ? {
                connect: args.data.passenger,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SecurityCheck)
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "delete",
    possession: "any",
  })
  async deleteSecurityCheck(
    @graphql.Args() args: DeleteSecurityCheckArgs
  ): Promise<SecurityCheck | null> {
    try {
      return await this.service.deleteSecurityCheck(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Flight, {
    nullable: true,
    name: "flight",
  })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "any",
  })
  async getFlight(
    @graphql.Parent() parent: SecurityCheck
  ): Promise<Flight | null> {
    const result = await this.service.getFlight(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Passenger, {
    nullable: true,
    name: "passenger",
  })
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "read",
    possession: "any",
  })
  async getPassenger(
    @graphql.Parent() parent: SecurityCheck
  ): Promise<Passenger | null> {
    const result = await this.service.getPassenger(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
