/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SecurityCheckService } from "../securityCheck.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SecurityCheckCreateInput } from "./SecurityCheckCreateInput";
import { SecurityCheck } from "./SecurityCheck";
import { SecurityCheckFindManyArgs } from "./SecurityCheckFindManyArgs";
import { SecurityCheckWhereUniqueInput } from "./SecurityCheckWhereUniqueInput";
import { SecurityCheckUpdateInput } from "./SecurityCheckUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SecurityCheckControllerBase {
  constructor(
    protected readonly service: SecurityCheckService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SecurityCheck })
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSecurityCheck(
    @common.Body() data: SecurityCheckCreateInput
  ): Promise<SecurityCheck> {
    return await this.service.createSecurityCheck({
      data: {
        ...data,

        flight: data.flight
          ? {
              connect: data.flight,
            }
          : undefined,

        passenger: data.passenger
          ? {
              connect: data.passenger,
            }
          : undefined,
      },
      select: {
        checkTime: true,
        cleared: true,
        createdAt: true,
        documentVerified: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        luggageScanResult: true,
        officerName: true,

        passenger: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SecurityCheck] })
  @ApiNestedQuery(SecurityCheckFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async securityChecks(
    @common.Req() request: Request
  ): Promise<SecurityCheck[]> {
    const args = plainToClass(SecurityCheckFindManyArgs, request.query);
    return this.service.securityChecks({
      ...args,
      select: {
        checkTime: true,
        cleared: true,
        createdAt: true,
        documentVerified: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        luggageScanResult: true,
        officerName: true,

        passenger: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SecurityCheck })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async securityCheck(
    @common.Param() params: SecurityCheckWhereUniqueInput
  ): Promise<SecurityCheck | null> {
    const result = await this.service.securityCheck({
      where: params,
      select: {
        checkTime: true,
        cleared: true,
        createdAt: true,
        documentVerified: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        luggageScanResult: true,
        officerName: true,

        passenger: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SecurityCheck })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSecurityCheck(
    @common.Param() params: SecurityCheckWhereUniqueInput,
    @common.Body() data: SecurityCheckUpdateInput
  ): Promise<SecurityCheck | null> {
    try {
      return await this.service.updateSecurityCheck({
        where: params,
        data: {
          ...data,

          flight: data.flight
            ? {
                connect: data.flight,
              }
            : undefined,

          passenger: data.passenger
            ? {
                connect: data.passenger,
              }
            : undefined,
        },
        select: {
          checkTime: true,
          cleared: true,
          createdAt: true,
          documentVerified: true,

          flight: {
            select: {
              id: true,
            },
          },

          id: true,
          luggageScanResult: true,
          officerName: true,

          passenger: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SecurityCheck })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSecurityCheck(
    @common.Param() params: SecurityCheckWhereUniqueInput
  ): Promise<SecurityCheck | null> {
    try {
      return await this.service.deleteSecurityCheck({
        where: params,
        select: {
          checkTime: true,
          cleared: true,
          createdAt: true,
          documentVerified: true,

          flight: {
            select: {
              id: true,
            },
          },

          id: true,
          luggageScanResult: true,
          officerName: true,

          passenger: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
