/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PassengerService } from "../passenger.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PassengerCreateInput } from "./PassengerCreateInput";
import { Passenger } from "./Passenger";
import { PassengerFindManyArgs } from "./PassengerFindManyArgs";
import { PassengerWhereUniqueInput } from "./PassengerWhereUniqueInput";
import { PassengerUpdateInput } from "./PassengerUpdateInput";
import { SecurityCheckFindManyArgs } from "../../securityCheck/base/SecurityCheckFindManyArgs";
import { SecurityCheck } from "../../securityCheck/base/SecurityCheck";
import { SecurityCheckWhereUniqueInput } from "../../securityCheck/base/SecurityCheckWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PassengerControllerBase {
  constructor(
    protected readonly service: PassengerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Passenger })
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPassenger(
    @common.Body() data: PassengerCreateInput
  ): Promise<Passenger> {
    return await this.service.createPassenger({
      data: {
        ...data,

        flight: data.flight
          ? {
              connect: data.flight,
            }
          : undefined,
      },
      select: {
        boardingPassId: true,
        createdAt: true,
        firstName: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        lastName: true,
        nationality: true,
        passportNumber: true,
        seatNumber: true,
        updatedAt: true,
        visaStatus: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Passenger] })
  @ApiNestedQuery(PassengerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async passengers(@common.Req() request: Request): Promise<Passenger[]> {
    const args = plainToClass(PassengerFindManyArgs, request.query);
    return this.service.passengers({
      ...args,
      select: {
        boardingPassId: true,
        createdAt: true,
        firstName: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        lastName: true,
        nationality: true,
        passportNumber: true,
        seatNumber: true,
        updatedAt: true,
        visaStatus: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Passenger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async passenger(
    @common.Param() params: PassengerWhereUniqueInput
  ): Promise<Passenger | null> {
    const result = await this.service.passenger({
      where: params,
      select: {
        boardingPassId: true,
        createdAt: true,
        firstName: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        lastName: true,
        nationality: true,
        passportNumber: true,
        seatNumber: true,
        updatedAt: true,
        visaStatus: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Passenger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePassenger(
    @common.Param() params: PassengerWhereUniqueInput,
    @common.Body() data: PassengerUpdateInput
  ): Promise<Passenger | null> {
    try {
      return await this.service.updatePassenger({
        where: params,
        data: {
          ...data,

          flight: data.flight
            ? {
                connect: data.flight,
              }
            : undefined,
        },
        select: {
          boardingPassId: true,
          createdAt: true,
          firstName: true,

          flight: {
            select: {
              id: true,
            },
          },

          id: true,
          lastName: true,
          nationality: true,
          passportNumber: true,
          seatNumber: true,
          updatedAt: true,
          visaStatus: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Passenger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePassenger(
    @common.Param() params: PassengerWhereUniqueInput
  ): Promise<Passenger | null> {
    try {
      return await this.service.deletePassenger({
        where: params,
        select: {
          boardingPassId: true,
          createdAt: true,
          firstName: true,

          flight: {
            select: {
              id: true,
            },
          },

          id: true,
          lastName: true,
          nationality: true,
          passportNumber: true,
          seatNumber: true,
          updatedAt: true,
          visaStatus: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/securityChecks")
  @ApiNestedQuery(SecurityCheckFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "any",
  })
  async findSecurityChecks(
    @common.Req() request: Request,
    @common.Param() params: PassengerWhereUniqueInput
  ): Promise<SecurityCheck[]> {
    const query = plainToClass(SecurityCheckFindManyArgs, request.query);
    const results = await this.service.findSecurityChecks(params.id, {
      ...query,
      select: {
        checkTime: true,
        cleared: true,
        createdAt: true,
        documentVerified: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        luggageScanResult: true,
        officerName: true,

        passenger: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/securityChecks")
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "update",
    possession: "any",
  })
  async connectSecurityChecks(
    @common.Param() params: PassengerWhereUniqueInput,
    @common.Body() body: SecurityCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securityChecks: {
        connect: body,
      },
    };
    await this.service.updatePassenger({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/securityChecks")
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "update",
    possession: "any",
  })
  async updateSecurityChecks(
    @common.Param() params: PassengerWhereUniqueInput,
    @common.Body() body: SecurityCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securityChecks: {
        set: body,
      },
    };
    await this.service.updatePassenger({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/securityChecks")
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "update",
    possession: "any",
  })
  async disconnectSecurityChecks(
    @common.Param() params: PassengerWhereUniqueInput,
    @common.Body() body: SecurityCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securityChecks: {
        disconnect: body,
      },
    };
    await this.service.updatePassenger({
      where: params,
      data,
      select: { id: true },
    });
  }
}
