/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Passenger } from "./Passenger";
import { PassengerCountArgs } from "./PassengerCountArgs";
import { PassengerFindManyArgs } from "./PassengerFindManyArgs";
import { PassengerFindUniqueArgs } from "./PassengerFindUniqueArgs";
import { CreatePassengerArgs } from "./CreatePassengerArgs";
import { UpdatePassengerArgs } from "./UpdatePassengerArgs";
import { DeletePassengerArgs } from "./DeletePassengerArgs";
import { SecurityCheckFindManyArgs } from "../../securityCheck/base/SecurityCheckFindManyArgs";
import { SecurityCheck } from "../../securityCheck/base/SecurityCheck";
import { Flight } from "../../flight/base/Flight";
import { PassengerService } from "../passenger.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Passenger)
export class PassengerResolverBase {
  constructor(
    protected readonly service: PassengerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "read",
    possession: "any",
  })
  async _passengersMeta(
    @graphql.Args() args: PassengerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Passenger])
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "read",
    possession: "any",
  })
  async passengers(
    @graphql.Args() args: PassengerFindManyArgs
  ): Promise<Passenger[]> {
    return this.service.passengers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Passenger, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "read",
    possession: "own",
  })
  async passenger(
    @graphql.Args() args: PassengerFindUniqueArgs
  ): Promise<Passenger | null> {
    const result = await this.service.passenger(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Passenger)
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "create",
    possession: "any",
  })
  async createPassenger(
    @graphql.Args() args: CreatePassengerArgs
  ): Promise<Passenger> {
    return await this.service.createPassenger({
      ...args,
      data: {
        ...args.data,

        flight: args.data.flight
          ? {
              connect: args.data.flight,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Passenger)
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "update",
    possession: "any",
  })
  async updatePassenger(
    @graphql.Args() args: UpdatePassengerArgs
  ): Promise<Passenger | null> {
    try {
      return await this.service.updatePassenger({
        ...args,
        data: {
          ...args.data,

          flight: args.data.flight
            ? {
                connect: args.data.flight,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Passenger)
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "delete",
    possession: "any",
  })
  async deletePassenger(
    @graphql.Args() args: DeletePassengerArgs
  ): Promise<Passenger | null> {
    try {
      return await this.service.deletePassenger(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SecurityCheck], { name: "securityChecks" })
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "any",
  })
  async findSecurityChecks(
    @graphql.Parent() parent: Passenger,
    @graphql.Args() args: SecurityCheckFindManyArgs
  ): Promise<SecurityCheck[]> {
    const results = await this.service.findSecurityChecks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Flight, {
    nullable: true,
    name: "flight",
  })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "any",
  })
  async getFlight(@graphql.Parent() parent: Passenger): Promise<Flight | null> {
    const result = await this.service.getFlight(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
