/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  VesselCrew as PrismaVesselCrew,
  Vessel as PrismaVessel,
} from "@prisma/client";

export class VesselCrewServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.VesselCrewCountArgs, "select">
  ): Promise<number> {
    return this.prisma.vesselCrew.count(args);
  }

  async vesselCrews(
    args: Prisma.VesselCrewFindManyArgs
  ): Promise<PrismaVesselCrew[]> {
    return this.prisma.vesselCrew.findMany(args);
  }
  async vesselCrew(
    args: Prisma.VesselCrewFindUniqueArgs
  ): Promise<PrismaVesselCrew | null> {
    return this.prisma.vesselCrew.findUnique(args);
  }
  async createVesselCrew(
    args: Prisma.VesselCrewCreateArgs
  ): Promise<PrismaVesselCrew> {
    return this.prisma.vesselCrew.create(args);
  }
  async updateVesselCrew(
    args: Prisma.VesselCrewUpdateArgs
  ): Promise<PrismaVesselCrew> {
    return this.prisma.vesselCrew.update(args);
  }
  async deleteVesselCrew(
    args: Prisma.VesselCrewDeleteArgs
  ): Promise<PrismaVesselCrew> {
    return this.prisma.vesselCrew.delete(args);
  }

  async getVessel(parentId: string): Promise<PrismaVessel | null> {
    return this.prisma.vesselCrew
      .findUnique({
        where: { id: parentId },
      })
      .vessel();
  }
}
