/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { VesselCrew } from "./VesselCrew";
import { VesselCrewCountArgs } from "./VesselCrewCountArgs";
import { VesselCrewFindManyArgs } from "./VesselCrewFindManyArgs";
import { VesselCrewFindUniqueArgs } from "./VesselCrewFindUniqueArgs";
import { CreateVesselCrewArgs } from "./CreateVesselCrewArgs";
import { UpdateVesselCrewArgs } from "./UpdateVesselCrewArgs";
import { DeleteVesselCrewArgs } from "./DeleteVesselCrewArgs";
import { Vessel } from "../../vessel/base/Vessel";
import { VesselCrewService } from "../vesselCrew.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => VesselCrew)
export class VesselCrewResolverBase {
  constructor(
    protected readonly service: VesselCrewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "read",
    possession: "any",
  })
  async _vesselCrewsMeta(
    @graphql.Args() args: VesselCrewCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [VesselCrew])
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "read",
    possession: "any",
  })
  async vesselCrews(
    @graphql.Args() args: VesselCrewFindManyArgs
  ): Promise<VesselCrew[]> {
    return this.service.vesselCrews(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => VesselCrew, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "read",
    possession: "own",
  })
  async vesselCrew(
    @graphql.Args() args: VesselCrewFindUniqueArgs
  ): Promise<VesselCrew | null> {
    const result = await this.service.vesselCrew(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VesselCrew)
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "create",
    possession: "any",
  })
  async createVesselCrew(
    @graphql.Args() args: CreateVesselCrewArgs
  ): Promise<VesselCrew> {
    return await this.service.createVesselCrew({
      ...args,
      data: {
        ...args.data,

        vessel: args.data.vessel
          ? {
              connect: args.data.vessel,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VesselCrew)
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "update",
    possession: "any",
  })
  async updateVesselCrew(
    @graphql.Args() args: UpdateVesselCrewArgs
  ): Promise<VesselCrew | null> {
    try {
      return await this.service.updateVesselCrew({
        ...args,
        data: {
          ...args.data,

          vessel: args.data.vessel
            ? {
                connect: args.data.vessel,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VesselCrew)
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "delete",
    possession: "any",
  })
  async deleteVesselCrew(
    @graphql.Args() args: DeleteVesselCrewArgs
  ): Promise<VesselCrew | null> {
    try {
      return await this.service.deleteVesselCrew(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Vessel, {
    nullable: true,
    name: "vessel",
  })
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "read",
    possession: "any",
  })
  async getVessel(
    @graphql.Parent() parent: VesselCrew
  ): Promise<Vessel | null> {
    const result = await this.service.getVessel(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
