/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VesselCrewService } from "../vesselCrew.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VesselCrewCreateInput } from "./VesselCrewCreateInput";
import { VesselCrew } from "./VesselCrew";
import { VesselCrewFindManyArgs } from "./VesselCrewFindManyArgs";
import { VesselCrewWhereUniqueInput } from "./VesselCrewWhereUniqueInput";
import { VesselCrewUpdateInput } from "./VesselCrewUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VesselCrewControllerBase {
  constructor(
    protected readonly service: VesselCrewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VesselCrew })
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVesselCrew(
    @common.Body() data: VesselCrewCreateInput
  ): Promise<VesselCrew> {
    return await this.service.createVesselCrew({
      data: {
        ...data,

        vessel: data.vessel
          ? {
              connect: data.vessel,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        nationality: true,
        passportNumber: true,
        role: true,
        updatedAt: true,

        vessel: {
          select: {
            id: true,
          },
        },

        visaStatus: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VesselCrew] })
  @ApiNestedQuery(VesselCrewFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vesselCrews(@common.Req() request: Request): Promise<VesselCrew[]> {
    const args = plainToClass(VesselCrewFindManyArgs, request.query);
    return this.service.vesselCrews({
      ...args,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        nationality: true,
        passportNumber: true,
        role: true,
        updatedAt: true,

        vessel: {
          select: {
            id: true,
          },
        },

        visaStatus: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VesselCrew })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vesselCrew(
    @common.Param() params: VesselCrewWhereUniqueInput
  ): Promise<VesselCrew | null> {
    const result = await this.service.vesselCrew({
      where: params,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        nationality: true,
        passportNumber: true,
        role: true,
        updatedAt: true,

        vessel: {
          select: {
            id: true,
          },
        },

        visaStatus: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VesselCrew })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVesselCrew(
    @common.Param() params: VesselCrewWhereUniqueInput,
    @common.Body() data: VesselCrewUpdateInput
  ): Promise<VesselCrew | null> {
    try {
      return await this.service.updateVesselCrew({
        where: params,
        data: {
          ...data,

          vessel: data.vessel
            ? {
                connect: data.vessel,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          firstName: true,
          id: true,
          lastName: true,
          nationality: true,
          passportNumber: true,
          role: true,
          updatedAt: true,

          vessel: {
            select: {
              id: true,
            },
          },

          visaStatus: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VesselCrew })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVesselCrew(
    @common.Param() params: VesselCrewWhereUniqueInput
  ): Promise<VesselCrew | null> {
    try {
      return await this.service.deleteVesselCrew({
        where: params,
        select: {
          createdAt: true,
          firstName: true,
          id: true,
          lastName: true,
          nationality: true,
          passportNumber: true,
          role: true,
          updatedAt: true,

          vessel: {
            select: {
              id: true,
            },
          },

          visaStatus: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
