/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Flight } from "./Flight";
import { FlightCountArgs } from "./FlightCountArgs";
import { FlightFindManyArgs } from "./FlightFindManyArgs";
import { FlightFindUniqueArgs } from "./FlightFindUniqueArgs";
import { CreateFlightArgs } from "./CreateFlightArgs";
import { UpdateFlightArgs } from "./UpdateFlightArgs";
import { DeleteFlightArgs } from "./DeleteFlightArgs";
import { PassengerFindManyArgs } from "../../passenger/base/PassengerFindManyArgs";
import { Passenger } from "../../passenger/base/Passenger";
import { SecurityCheckFindManyArgs } from "../../securityCheck/base/SecurityCheckFindManyArgs";
import { SecurityCheck } from "../../securityCheck/base/SecurityCheck";
import { FlightService } from "../flight.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Flight)
export class FlightResolverBase {
  constructor(
    protected readonly service: FlightService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "any",
  })
  async _flightsMeta(
    @graphql.Args() args: FlightCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Flight])
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "any",
  })
  async flights(@graphql.Args() args: FlightFindManyArgs): Promise<Flight[]> {
    return this.service.flights(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Flight, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "own",
  })
  async flight(
    @graphql.Args() args: FlightFindUniqueArgs
  ): Promise<Flight | null> {
    const result = await this.service.flight(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Flight)
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "create",
    possession: "any",
  })
  async createFlight(@graphql.Args() args: CreateFlightArgs): Promise<Flight> {
    return await this.service.createFlight({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Flight)
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async updateFlight(
    @graphql.Args() args: UpdateFlightArgs
  ): Promise<Flight | null> {
    try {
      return await this.service.updateFlight({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Flight)
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "delete",
    possession: "any",
  })
  async deleteFlight(
    @graphql.Args() args: DeleteFlightArgs
  ): Promise<Flight | null> {
    try {
      return await this.service.deleteFlight(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Passenger], { name: "passengers" })
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "read",
    possession: "any",
  })
  async findPassengers(
    @graphql.Parent() parent: Flight,
    @graphql.Args() args: PassengerFindManyArgs
  ): Promise<Passenger[]> {
    const results = await this.service.findPassengers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SecurityCheck], { name: "securityChecks" })
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "any",
  })
  async findSecurityChecks(
    @graphql.Parent() parent: Flight,
    @graphql.Args() args: SecurityCheckFindManyArgs
  ): Promise<SecurityCheck[]> {
    const results = await this.service.findSecurityChecks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
