/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { PassengerUpdateManyWithoutFlightsInput } from "./PassengerUpdateManyWithoutFlightsInput";
import { Type } from "class-transformer";
import { SecurityCheckUpdateManyWithoutFlightsInput } from "./SecurityCheckUpdateManyWithoutFlightsInput";

@InputType()
class FlightUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  airline?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  destinationAirport?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  flightNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  originAirport?: string | null;

  @ApiProperty({
    required: false,
    type: () => PassengerUpdateManyWithoutFlightsInput,
  })
  @ValidateNested()
  @Type(() => PassengerUpdateManyWithoutFlightsInput)
  @IsOptional()
  @Field(() => PassengerUpdateManyWithoutFlightsInput, {
    nullable: true,
  })
  passengers?: PassengerUpdateManyWithoutFlightsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  scheduledArrival?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  scheduledDeparture?: Date | null;

  @ApiProperty({
    required: false,
    type: () => SecurityCheckUpdateManyWithoutFlightsInput,
  })
  @ValidateNested()
  @Type(() => SecurityCheckUpdateManyWithoutFlightsInput)
  @IsOptional()
  @Field(() => SecurityCheckUpdateManyWithoutFlightsInput, {
    nullable: true,
  })
  securityChecks?: SecurityCheckUpdateManyWithoutFlightsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;
}

export { FlightUpdateInput as FlightUpdateInput };
