/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FlightService } from "../flight.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FlightCreateInput } from "./FlightCreateInput";
import { Flight } from "./Flight";
import { FlightFindManyArgs } from "./FlightFindManyArgs";
import { FlightWhereUniqueInput } from "./FlightWhereUniqueInput";
import { FlightUpdateInput } from "./FlightUpdateInput";
import { PassengerFindManyArgs } from "../../passenger/base/PassengerFindManyArgs";
import { Passenger } from "../../passenger/base/Passenger";
import { PassengerWhereUniqueInput } from "../../passenger/base/PassengerWhereUniqueInput";
import { SecurityCheckFindManyArgs } from "../../securityCheck/base/SecurityCheckFindManyArgs";
import { SecurityCheck } from "../../securityCheck/base/SecurityCheck";
import { SecurityCheckWhereUniqueInput } from "../../securityCheck/base/SecurityCheckWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FlightControllerBase {
  constructor(
    protected readonly service: FlightService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Flight })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFlight(@common.Body() data: FlightCreateInput): Promise<Flight> {
    return await this.service.createFlight({
      data: data,
      select: {
        airline: true,
        createdAt: true,
        destinationAirport: true,
        flightNumber: true,
        id: true,
        originAirport: true,
        scheduledArrival: true,
        scheduledDeparture: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Flight] })
  @ApiNestedQuery(FlightFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async flights(@common.Req() request: Request): Promise<Flight[]> {
    const args = plainToClass(FlightFindManyArgs, request.query);
    return this.service.flights({
      ...args,
      select: {
        airline: true,
        createdAt: true,
        destinationAirport: true,
        flightNumber: true,
        id: true,
        originAirport: true,
        scheduledArrival: true,
        scheduledDeparture: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async flight(
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Flight | null> {
    const result = await this.service.flight({
      where: params,
      select: {
        airline: true,
        createdAt: true,
        destinationAirport: true,
        flightNumber: true,
        id: true,
        originAirport: true,
        scheduledArrival: true,
        scheduledDeparture: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFlight(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() data: FlightUpdateInput
  ): Promise<Flight | null> {
    try {
      return await this.service.updateFlight({
        where: params,
        data: data,
        select: {
          airline: true,
          createdAt: true,
          destinationAirport: true,
          flightNumber: true,
          id: true,
          originAirport: true,
          scheduledArrival: true,
          scheduledDeparture: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFlight(
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Flight | null> {
    try {
      return await this.service.deleteFlight({
        where: params,
        select: {
          airline: true,
          createdAt: true,
          destinationAirport: true,
          flightNumber: true,
          id: true,
          originAirport: true,
          scheduledArrival: true,
          scheduledDeparture: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/passengers")
  @ApiNestedQuery(PassengerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Passenger",
    action: "read",
    possession: "any",
  })
  async findPassengers(
    @common.Req() request: Request,
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Passenger[]> {
    const query = plainToClass(PassengerFindManyArgs, request.query);
    const results = await this.service.findPassengers(params.id, {
      ...query,
      select: {
        boardingPassId: true,
        createdAt: true,
        firstName: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        lastName: true,
        nationality: true,
        passportNumber: true,
        seatNumber: true,
        updatedAt: true,
        visaStatus: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/passengers")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async connectPassengers(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: PassengerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passengers: {
        connect: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/passengers")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async updatePassengers(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: PassengerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passengers: {
        set: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/passengers")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async disconnectPassengers(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: PassengerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passengers: {
        disconnect: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/securityChecks")
  @ApiNestedQuery(SecurityCheckFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SecurityCheck",
    action: "read",
    possession: "any",
  })
  async findSecurityChecks(
    @common.Req() request: Request,
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<SecurityCheck[]> {
    const query = plainToClass(SecurityCheckFindManyArgs, request.query);
    const results = await this.service.findSecurityChecks(params.id, {
      ...query,
      select: {
        checkTime: true,
        cleared: true,
        createdAt: true,
        documentVerified: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        luggageScanResult: true,
        officerName: true,

        passenger: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/securityChecks")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async connectSecurityChecks(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: SecurityCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securityChecks: {
        connect: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/securityChecks")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async updateSecurityChecks(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: SecurityCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securityChecks: {
        set: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/securityChecks")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async disconnectSecurityChecks(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: SecurityCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securityChecks: {
        disconnect: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }
}
