/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GoodsDeclarationService } from "../goodsDeclaration.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GoodsDeclarationCreateInput } from "./GoodsDeclarationCreateInput";
import { GoodsDeclaration } from "./GoodsDeclaration";
import { GoodsDeclarationFindManyArgs } from "./GoodsDeclarationFindManyArgs";
import { GoodsDeclarationWhereUniqueInput } from "./GoodsDeclarationWhereUniqueInput";
import { GoodsDeclarationUpdateInput } from "./GoodsDeclarationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GoodsDeclarationControllerBase {
  constructor(
    protected readonly service: GoodsDeclarationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GoodsDeclaration })
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGoodsDeclaration(
    @common.Body() data: GoodsDeclarationCreateInput
  ): Promise<GoodsDeclaration> {
    return await this.service.createGoodsDeclaration({
      data: {
        ...data,

        landVehicle: data.landVehicle
          ? {
              connect: data.landVehicle,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        customsStatus: true,
        declarationNumber: true,
        description: true,
        id: true,

        landVehicle: {
          select: {
            id: true,
          },
        },

        ownerName: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GoodsDeclaration] })
  @ApiNestedQuery(GoodsDeclarationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async goodsDeclarations(
    @common.Req() request: Request
  ): Promise<GoodsDeclaration[]> {
    const args = plainToClass(GoodsDeclarationFindManyArgs, request.query);
    return this.service.goodsDeclarations({
      ...args,
      select: {
        createdAt: true,
        customsStatus: true,
        declarationNumber: true,
        description: true,
        id: true,

        landVehicle: {
          select: {
            id: true,
          },
        },

        ownerName: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GoodsDeclaration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async goodsDeclaration(
    @common.Param() params: GoodsDeclarationWhereUniqueInput
  ): Promise<GoodsDeclaration | null> {
    const result = await this.service.goodsDeclaration({
      where: params,
      select: {
        createdAt: true,
        customsStatus: true,
        declarationNumber: true,
        description: true,
        id: true,

        landVehicle: {
          select: {
            id: true,
          },
        },

        ownerName: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GoodsDeclaration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGoodsDeclaration(
    @common.Param() params: GoodsDeclarationWhereUniqueInput,
    @common.Body() data: GoodsDeclarationUpdateInput
  ): Promise<GoodsDeclaration | null> {
    try {
      return await this.service.updateGoodsDeclaration({
        where: params,
        data: {
          ...data,

          landVehicle: data.landVehicle
            ? {
                connect: data.landVehicle,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          customsStatus: true,
          declarationNumber: true,
          description: true,
          id: true,

          landVehicle: {
            select: {
              id: true,
            },
          },

          ownerName: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GoodsDeclaration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGoodsDeclaration(
    @common.Param() params: GoodsDeclarationWhereUniqueInput
  ): Promise<GoodsDeclaration | null> {
    try {
      return await this.service.deleteGoodsDeclaration({
        where: params,
        select: {
          createdAt: true,
          customsStatus: true,
          declarationNumber: true,
          description: true,
          id: true,

          landVehicle: {
            select: {
              id: true,
            },
          },

          ownerName: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
