/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  GoodsDeclaration as PrismaGoodsDeclaration,
  LandVehicle as PrismaLandVehicle,
} from "@prisma/client";

export class GoodsDeclarationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.GoodsDeclarationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.goodsDeclaration.count(args);
  }

  async goodsDeclarations(
    args: Prisma.GoodsDeclarationFindManyArgs
  ): Promise<PrismaGoodsDeclaration[]> {
    return this.prisma.goodsDeclaration.findMany(args);
  }
  async goodsDeclaration(
    args: Prisma.GoodsDeclarationFindUniqueArgs
  ): Promise<PrismaGoodsDeclaration | null> {
    return this.prisma.goodsDeclaration.findUnique(args);
  }
  async createGoodsDeclaration(
    args: Prisma.GoodsDeclarationCreateArgs
  ): Promise<PrismaGoodsDeclaration> {
    return this.prisma.goodsDeclaration.create(args);
  }
  async updateGoodsDeclaration(
    args: Prisma.GoodsDeclarationUpdateArgs
  ): Promise<PrismaGoodsDeclaration> {
    return this.prisma.goodsDeclaration.update(args);
  }
  async deleteGoodsDeclaration(
    args: Prisma.GoodsDeclarationDeleteArgs
  ): Promise<PrismaGoodsDeclaration> {
    return this.prisma.goodsDeclaration.delete(args);
  }

  async getLandVehicle(parentId: string): Promise<PrismaLandVehicle | null> {
    return this.prisma.goodsDeclaration
      .findUnique({
        where: { id: parentId },
      })
      .landVehicle();
  }
}
