/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { GoodsDeclaration } from "./GoodsDeclaration";
import { GoodsDeclarationCountArgs } from "./GoodsDeclarationCountArgs";
import { GoodsDeclarationFindManyArgs } from "./GoodsDeclarationFindManyArgs";
import { GoodsDeclarationFindUniqueArgs } from "./GoodsDeclarationFindUniqueArgs";
import { CreateGoodsDeclarationArgs } from "./CreateGoodsDeclarationArgs";
import { UpdateGoodsDeclarationArgs } from "./UpdateGoodsDeclarationArgs";
import { DeleteGoodsDeclarationArgs } from "./DeleteGoodsDeclarationArgs";
import { LandVehicle } from "../../landVehicle/base/LandVehicle";
import { GoodsDeclarationService } from "../goodsDeclaration.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => GoodsDeclaration)
export class GoodsDeclarationResolverBase {
  constructor(
    protected readonly service: GoodsDeclarationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "read",
    possession: "any",
  })
  async _goodsDeclarationsMeta(
    @graphql.Args() args: GoodsDeclarationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [GoodsDeclaration])
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "read",
    possession: "any",
  })
  async goodsDeclarations(
    @graphql.Args() args: GoodsDeclarationFindManyArgs
  ): Promise<GoodsDeclaration[]> {
    return this.service.goodsDeclarations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => GoodsDeclaration, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "read",
    possession: "own",
  })
  async goodsDeclaration(
    @graphql.Args() args: GoodsDeclarationFindUniqueArgs
  ): Promise<GoodsDeclaration | null> {
    const result = await this.service.goodsDeclaration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => GoodsDeclaration)
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "create",
    possession: "any",
  })
  async createGoodsDeclaration(
    @graphql.Args() args: CreateGoodsDeclarationArgs
  ): Promise<GoodsDeclaration> {
    return await this.service.createGoodsDeclaration({
      ...args,
      data: {
        ...args.data,

        landVehicle: args.data.landVehicle
          ? {
              connect: args.data.landVehicle,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => GoodsDeclaration)
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "update",
    possession: "any",
  })
  async updateGoodsDeclaration(
    @graphql.Args() args: UpdateGoodsDeclarationArgs
  ): Promise<GoodsDeclaration | null> {
    try {
      return await this.service.updateGoodsDeclaration({
        ...args,
        data: {
          ...args.data,

          landVehicle: args.data.landVehicle
            ? {
                connect: args.data.landVehicle,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GoodsDeclaration)
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "delete",
    possession: "any",
  })
  async deleteGoodsDeclaration(
    @graphql.Args() args: DeleteGoodsDeclarationArgs
  ): Promise<GoodsDeclaration | null> {
    try {
      return await this.service.deleteGoodsDeclaration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => LandVehicle, {
    nullable: true,
    name: "landVehicle",
  })
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "read",
    possession: "any",
  })
  async getLandVehicle(
    @graphql.Parent() parent: GoodsDeclaration
  ): Promise<LandVehicle | null> {
    const result = await this.service.getLandVehicle(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
