/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LandVehicleService } from "../landVehicle.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LandVehicleCreateInput } from "./LandVehicleCreateInput";
import { LandVehicle } from "./LandVehicle";
import { LandVehicleFindManyArgs } from "./LandVehicleFindManyArgs";
import { LandVehicleWhereUniqueInput } from "./LandVehicleWhereUniqueInput";
import { LandVehicleUpdateInput } from "./LandVehicleUpdateInput";
import { GoodsDeclarationFindManyArgs } from "../../goodsDeclaration/base/GoodsDeclarationFindManyArgs";
import { GoodsDeclaration } from "../../goodsDeclaration/base/GoodsDeclaration";
import { GoodsDeclarationWhereUniqueInput } from "../../goodsDeclaration/base/GoodsDeclarationWhereUniqueInput";
import { PersonFindManyArgs } from "../../person/base/PersonFindManyArgs";
import { Person } from "../../person/base/Person";
import { PersonWhereUniqueInput } from "../../person/base/PersonWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LandVehicleControllerBase {
  constructor(
    protected readonly service: LandVehicleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LandVehicle })
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLandVehicle(
    @common.Body() data: LandVehicleCreateInput
  ): Promise<LandVehicle> {
    return await this.service.createLandVehicle({
      data: data,
      select: {
        createdAt: true,
        entryPoint: true,
        entryTime: true,
        id: true,
        nationality: true,
        ownerName: true,
        plateNumber: true,
        status: true,
        updatedAt: true,
        vehicleType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LandVehicle] })
  @ApiNestedQuery(LandVehicleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async landVehicles(@common.Req() request: Request): Promise<LandVehicle[]> {
    const args = plainToClass(LandVehicleFindManyArgs, request.query);
    return this.service.landVehicles({
      ...args,
      select: {
        createdAt: true,
        entryPoint: true,
        entryTime: true,
        id: true,
        nationality: true,
        ownerName: true,
        plateNumber: true,
        status: true,
        updatedAt: true,
        vehicleType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LandVehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async landVehicle(
    @common.Param() params: LandVehicleWhereUniqueInput
  ): Promise<LandVehicle | null> {
    const result = await this.service.landVehicle({
      where: params,
      select: {
        createdAt: true,
        entryPoint: true,
        entryTime: true,
        id: true,
        nationality: true,
        ownerName: true,
        plateNumber: true,
        status: true,
        updatedAt: true,
        vehicleType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LandVehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLandVehicle(
    @common.Param() params: LandVehicleWhereUniqueInput,
    @common.Body() data: LandVehicleUpdateInput
  ): Promise<LandVehicle | null> {
    try {
      return await this.service.updateLandVehicle({
        where: params,
        data: data,
        select: {
          createdAt: true,
          entryPoint: true,
          entryTime: true,
          id: true,
          nationality: true,
          ownerName: true,
          plateNumber: true,
          status: true,
          updatedAt: true,
          vehicleType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LandVehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLandVehicle(
    @common.Param() params: LandVehicleWhereUniqueInput
  ): Promise<LandVehicle | null> {
    try {
      return await this.service.deleteLandVehicle({
        where: params,
        select: {
          createdAt: true,
          entryPoint: true,
          entryTime: true,
          id: true,
          nationality: true,
          ownerName: true,
          plateNumber: true,
          status: true,
          updatedAt: true,
          vehicleType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/goodsDeclarations")
  @ApiNestedQuery(GoodsDeclarationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "read",
    possession: "any",
  })
  async findGoodsDeclarations(
    @common.Req() request: Request,
    @common.Param() params: LandVehicleWhereUniqueInput
  ): Promise<GoodsDeclaration[]> {
    const query = plainToClass(GoodsDeclarationFindManyArgs, request.query);
    const results = await this.service.findGoodsDeclarations(params.id, {
      ...query,
      select: {
        createdAt: true,
        customsStatus: true,
        declarationNumber: true,
        description: true,
        id: true,

        landVehicle: {
          select: {
            id: true,
          },
        },

        ownerName: true,
        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/goodsDeclarations")
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "update",
    possession: "any",
  })
  async connectGoodsDeclarations(
    @common.Param() params: LandVehicleWhereUniqueInput,
    @common.Body() body: GoodsDeclarationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      goodsDeclarations: {
        connect: body,
      },
    };
    await this.service.updateLandVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/goodsDeclarations")
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "update",
    possession: "any",
  })
  async updateGoodsDeclarations(
    @common.Param() params: LandVehicleWhereUniqueInput,
    @common.Body() body: GoodsDeclarationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      goodsDeclarations: {
        set: body,
      },
    };
    await this.service.updateLandVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/goodsDeclarations")
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "update",
    possession: "any",
  })
  async disconnectGoodsDeclarations(
    @common.Param() params: LandVehicleWhereUniqueInput,
    @common.Body() body: GoodsDeclarationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      goodsDeclarations: {
        disconnect: body,
      },
    };
    await this.service.updateLandVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/people")
  @ApiNestedQuery(PersonFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Person",
    action: "read",
    possession: "any",
  })
  async findPeople(
    @common.Req() request: Request,
    @common.Param() params: LandVehicleWhereUniqueInput
  ): Promise<Person[]> {
    const query = plainToClass(PersonFindManyArgs, request.query);
    const results = await this.service.findPeople(params.id, {
      ...query,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        idNumber: true,

        landVehicle: {
          select: {
            id: true,
          },
        },

        lastName: true,
        nationality: true,
        passportNumber: true,
        updatedAt: true,
        visaStatus: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/people")
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "update",
    possession: "any",
  })
  async connectPeople(
    @common.Param() params: LandVehicleWhereUniqueInput,
    @common.Body() body: PersonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      people: {
        connect: body,
      },
    };
    await this.service.updateLandVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/people")
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "update",
    possession: "any",
  })
  async updatePeople(
    @common.Param() params: LandVehicleWhereUniqueInput,
    @common.Body() body: PersonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      people: {
        set: body,
      },
    };
    await this.service.updateLandVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/people")
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "update",
    possession: "any",
  })
  async disconnectPeople(
    @common.Param() params: LandVehicleWhereUniqueInput,
    @common.Body() body: PersonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      people: {
        disconnect: body,
      },
    };
    await this.service.updateLandVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }
}
