/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { GoodsDeclarationUpdateManyWithoutLandVehiclesInput } from "./GoodsDeclarationUpdateManyWithoutLandVehiclesInput";
import { PersonUpdateManyWithoutLandVehiclesInput } from "./PersonUpdateManyWithoutLandVehiclesInput";

@InputType()
class LandVehicleUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  entryPoint?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  entryTime?: Date | null;

  @ApiProperty({
    required: false,
    type: () => GoodsDeclarationUpdateManyWithoutLandVehiclesInput,
  })
  @ValidateNested()
  @Type(() => GoodsDeclarationUpdateManyWithoutLandVehiclesInput)
  @IsOptional()
  @Field(() => GoodsDeclarationUpdateManyWithoutLandVehiclesInput, {
    nullable: true,
  })
  goodsDeclarations?: GoodsDeclarationUpdateManyWithoutLandVehiclesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nationality?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ownerName?: string | null;

  @ApiProperty({
    required: false,
    type: () => PersonUpdateManyWithoutLandVehiclesInput,
  })
  @ValidateNested()
  @Type(() => PersonUpdateManyWithoutLandVehiclesInput)
  @IsOptional()
  @Field(() => PersonUpdateManyWithoutLandVehiclesInput, {
    nullable: true,
  })
  people?: PersonUpdateManyWithoutLandVehiclesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  plateNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  vehicleType?: string | null;
}

export { LandVehicleUpdateInput as LandVehicleUpdateInput };
