/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  LandVehicle as PrismaLandVehicle,
  GoodsDeclaration as PrismaGoodsDeclaration,
  Person as PrismaPerson,
} from "@prisma/client";

export class LandVehicleServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LandVehicleCountArgs, "select">
  ): Promise<number> {
    return this.prisma.landVehicle.count(args);
  }

  async landVehicles(
    args: Prisma.LandVehicleFindManyArgs
  ): Promise<PrismaLandVehicle[]> {
    return this.prisma.landVehicle.findMany(args);
  }
  async landVehicle(
    args: Prisma.LandVehicleFindUniqueArgs
  ): Promise<PrismaLandVehicle | null> {
    return this.prisma.landVehicle.findUnique(args);
  }
  async createLandVehicle(
    args: Prisma.LandVehicleCreateArgs
  ): Promise<PrismaLandVehicle> {
    return this.prisma.landVehicle.create(args);
  }
  async updateLandVehicle(
    args: Prisma.LandVehicleUpdateArgs
  ): Promise<PrismaLandVehicle> {
    return this.prisma.landVehicle.update(args);
  }
  async deleteLandVehicle(
    args: Prisma.LandVehicleDeleteArgs
  ): Promise<PrismaLandVehicle> {
    return this.prisma.landVehicle.delete(args);
  }

  async findGoodsDeclarations(
    parentId: string,
    args: Prisma.GoodsDeclarationFindManyArgs
  ): Promise<PrismaGoodsDeclaration[]> {
    return this.prisma.landVehicle
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .goodsDeclarations(args);
  }

  async findPeople(
    parentId: string,
    args: Prisma.PersonFindManyArgs
  ): Promise<PrismaPerson[]> {
    return this.prisma.landVehicle
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .people(args);
  }
}
