/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { LandVehicle } from "./LandVehicle";
import { LandVehicleCountArgs } from "./LandVehicleCountArgs";
import { LandVehicleFindManyArgs } from "./LandVehicleFindManyArgs";
import { LandVehicleFindUniqueArgs } from "./LandVehicleFindUniqueArgs";
import { CreateLandVehicleArgs } from "./CreateLandVehicleArgs";
import { UpdateLandVehicleArgs } from "./UpdateLandVehicleArgs";
import { DeleteLandVehicleArgs } from "./DeleteLandVehicleArgs";
import { GoodsDeclarationFindManyArgs } from "../../goodsDeclaration/base/GoodsDeclarationFindManyArgs";
import { GoodsDeclaration } from "../../goodsDeclaration/base/GoodsDeclaration";
import { PersonFindManyArgs } from "../../person/base/PersonFindManyArgs";
import { Person } from "../../person/base/Person";
import { LandVehicleService } from "../landVehicle.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => LandVehicle)
export class LandVehicleResolverBase {
  constructor(
    protected readonly service: LandVehicleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "read",
    possession: "any",
  })
  async _landVehiclesMeta(
    @graphql.Args() args: LandVehicleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [LandVehicle])
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "read",
    possession: "any",
  })
  async landVehicles(
    @graphql.Args() args: LandVehicleFindManyArgs
  ): Promise<LandVehicle[]> {
    return this.service.landVehicles(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => LandVehicle, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "read",
    possession: "own",
  })
  async landVehicle(
    @graphql.Args() args: LandVehicleFindUniqueArgs
  ): Promise<LandVehicle | null> {
    const result = await this.service.landVehicle(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => LandVehicle)
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "create",
    possession: "any",
  })
  async createLandVehicle(
    @graphql.Args() args: CreateLandVehicleArgs
  ): Promise<LandVehicle> {
    return await this.service.createLandVehicle({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => LandVehicle)
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "update",
    possession: "any",
  })
  async updateLandVehicle(
    @graphql.Args() args: UpdateLandVehicleArgs
  ): Promise<LandVehicle | null> {
    try {
      return await this.service.updateLandVehicle({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LandVehicle)
  @nestAccessControl.UseRoles({
    resource: "LandVehicle",
    action: "delete",
    possession: "any",
  })
  async deleteLandVehicle(
    @graphql.Args() args: DeleteLandVehicleArgs
  ): Promise<LandVehicle | null> {
    try {
      return await this.service.deleteLandVehicle(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [GoodsDeclaration], { name: "goodsDeclarations" })
  @nestAccessControl.UseRoles({
    resource: "GoodsDeclaration",
    action: "read",
    possession: "any",
  })
  async findGoodsDeclarations(
    @graphql.Parent() parent: LandVehicle,
    @graphql.Args() args: GoodsDeclarationFindManyArgs
  ): Promise<GoodsDeclaration[]> {
    const results = await this.service.findGoodsDeclarations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Person], { name: "people" })
  @nestAccessControl.UseRoles({
    resource: "Person",
    action: "read",
    possession: "any",
  })
  async findPeople(
    @graphql.Parent() parent: LandVehicle,
    @graphql.Args() args: PersonFindManyArgs
  ): Promise<Person[]> {
    const results = await this.service.findPeople(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
