/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { GoodsDeclarationListRelationFilter } from "../../goodsDeclaration/base/GoodsDeclarationListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { PersonListRelationFilter } from "../../person/base/PersonListRelationFilter";

@InputType()
class LandVehicleWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  entryPoint?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  entryTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => GoodsDeclarationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GoodsDeclarationListRelationFilter)
  @IsOptional()
  @Field(() => GoodsDeclarationListRelationFilter, {
    nullable: true,
  })
  goodsDeclarations?: GoodsDeclarationListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nationality?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  ownerName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PersonListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PersonListRelationFilter)
  @IsOptional()
  @Field(() => PersonListRelationFilter, {
    nullable: true,
  })
  people?: PersonListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  plateNumber?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  status?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  vehicleType?: StringNullableFilter;
}

export { LandVehicleWhereInput as LandVehicleWhereInput };
