/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  AlertNotification as PrismaAlertNotification,
} from "@prisma/client";

export class AlertNotificationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AlertNotificationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.alertNotification.count(args);
  }

  async alertNotifications(
    args: Prisma.AlertNotificationFindManyArgs
  ): Promise<PrismaAlertNotification[]> {
    return this.prisma.alertNotification.findMany(args);
  }
  async alertNotification(
    args: Prisma.AlertNotificationFindUniqueArgs
  ): Promise<PrismaAlertNotification | null> {
    return this.prisma.alertNotification.findUnique(args);
  }
  async createAlertNotification(
    args: Prisma.AlertNotificationCreateArgs
  ): Promise<PrismaAlertNotification> {
    return this.prisma.alertNotification.create(args);
  }
  async updateAlertNotification(
    args: Prisma.AlertNotificationUpdateArgs
  ): Promise<PrismaAlertNotification> {
    return this.prisma.alertNotification.update(args);
  }
  async deleteAlertNotification(
    args: Prisma.AlertNotificationDeleteArgs
  ): Promise<PrismaAlertNotification> {
    return this.prisma.alertNotification.delete(args);
  }
}
