/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AlertNotificationService } from "../alertNotification.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AlertNotificationCreateInput } from "./AlertNotificationCreateInput";
import { AlertNotification } from "./AlertNotification";
import { AlertNotificationFindManyArgs } from "./AlertNotificationFindManyArgs";
import { AlertNotificationWhereUniqueInput } from "./AlertNotificationWhereUniqueInput";
import { AlertNotificationUpdateInput } from "./AlertNotificationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AlertNotificationControllerBase {
  constructor(
    protected readonly service: AlertNotificationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AlertNotification })
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAlertNotification(
    @common.Body() data: AlertNotificationCreateInput
  ): Promise<AlertNotification> {
    return await this.service.createAlertNotification({
      data: data,
      select: {
        actionRequired: true,
        createdAt: true,
        id: true,
        message: true,
        moduleField: true,
        severity: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AlertNotification] })
  @ApiNestedQuery(AlertNotificationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async alertNotifications(
    @common.Req() request: Request
  ): Promise<AlertNotification[]> {
    const args = plainToClass(AlertNotificationFindManyArgs, request.query);
    return this.service.alertNotifications({
      ...args,
      select: {
        actionRequired: true,
        createdAt: true,
        id: true,
        message: true,
        moduleField: true,
        severity: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AlertNotification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async alertNotification(
    @common.Param() params: AlertNotificationWhereUniqueInput
  ): Promise<AlertNotification | null> {
    const result = await this.service.alertNotification({
      where: params,
      select: {
        actionRequired: true,
        createdAt: true,
        id: true,
        message: true,
        moduleField: true,
        severity: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AlertNotification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAlertNotification(
    @common.Param() params: AlertNotificationWhereUniqueInput,
    @common.Body() data: AlertNotificationUpdateInput
  ): Promise<AlertNotification | null> {
    try {
      return await this.service.updateAlertNotification({
        where: params,
        data: data,
        select: {
          actionRequired: true,
          createdAt: true,
          id: true,
          message: true,
          moduleField: true,
          severity: true,
          status: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AlertNotification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAlertNotification(
    @common.Param() params: AlertNotificationWhereUniqueInput
  ): Promise<AlertNotification | null> {
    try {
      return await this.service.deleteAlertNotification({
        where: params,
        select: {
          actionRequired: true,
          createdAt: true,
          id: true,
          message: true,
          moduleField: true,
          severity: true,
          status: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
