/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AlertNotification } from "./AlertNotification";
import { AlertNotificationCountArgs } from "./AlertNotificationCountArgs";
import { AlertNotificationFindManyArgs } from "./AlertNotificationFindManyArgs";
import { AlertNotificationFindUniqueArgs } from "./AlertNotificationFindUniqueArgs";
import { CreateAlertNotificationArgs } from "./CreateAlertNotificationArgs";
import { UpdateAlertNotificationArgs } from "./UpdateAlertNotificationArgs";
import { DeleteAlertNotificationArgs } from "./DeleteAlertNotificationArgs";
import { AlertNotificationService } from "../alertNotification.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AlertNotification)
export class AlertNotificationResolverBase {
  constructor(
    protected readonly service: AlertNotificationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "read",
    possession: "any",
  })
  async _alertNotificationsMeta(
    @graphql.Args() args: AlertNotificationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AlertNotification])
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "read",
    possession: "any",
  })
  async alertNotifications(
    @graphql.Args() args: AlertNotificationFindManyArgs
  ): Promise<AlertNotification[]> {
    return this.service.alertNotifications(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AlertNotification, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "read",
    possession: "own",
  })
  async alertNotification(
    @graphql.Args() args: AlertNotificationFindUniqueArgs
  ): Promise<AlertNotification | null> {
    const result = await this.service.alertNotification(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AlertNotification)
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "create",
    possession: "any",
  })
  async createAlertNotification(
    @graphql.Args() args: CreateAlertNotificationArgs
  ): Promise<AlertNotification> {
    return await this.service.createAlertNotification({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AlertNotification)
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "update",
    possession: "any",
  })
  async updateAlertNotification(
    @graphql.Args() args: UpdateAlertNotificationArgs
  ): Promise<AlertNotification | null> {
    try {
      return await this.service.updateAlertNotification({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AlertNotification)
  @nestAccessControl.UseRoles({
    resource: "AlertNotification",
    action: "delete",
    possession: "any",
  })
  async deleteAlertNotification(
    @graphql.Args() args: DeleteAlertNotificationArgs
  ): Promise<AlertNotification | null> {
    try {
      return await this.service.deleteAlertNotification(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
