/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CargoManifest } from "./CargoManifest";
import { CargoManifestCountArgs } from "./CargoManifestCountArgs";
import { CargoManifestFindManyArgs } from "./CargoManifestFindManyArgs";
import { CargoManifestFindUniqueArgs } from "./CargoManifestFindUniqueArgs";
import { CreateCargoManifestArgs } from "./CreateCargoManifestArgs";
import { UpdateCargoManifestArgs } from "./UpdateCargoManifestArgs";
import { DeleteCargoManifestArgs } from "./DeleteCargoManifestArgs";
import { Vessel } from "../../vessel/base/Vessel";
import { CargoManifestService } from "../cargoManifest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CargoManifest)
export class CargoManifestResolverBase {
  constructor(
    protected readonly service: CargoManifestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "read",
    possession: "any",
  })
  async _cargoManifestsMeta(
    @graphql.Args() args: CargoManifestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CargoManifest])
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "read",
    possession: "any",
  })
  async cargoManifests(
    @graphql.Args() args: CargoManifestFindManyArgs
  ): Promise<CargoManifest[]> {
    return this.service.cargoManifests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CargoManifest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "read",
    possession: "own",
  })
  async cargoManifest(
    @graphql.Args() args: CargoManifestFindUniqueArgs
  ): Promise<CargoManifest | null> {
    const result = await this.service.cargoManifest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CargoManifest)
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "create",
    possession: "any",
  })
  async createCargoManifest(
    @graphql.Args() args: CreateCargoManifestArgs
  ): Promise<CargoManifest> {
    return await this.service.createCargoManifest({
      ...args,
      data: {
        ...args.data,

        vessel: args.data.vessel
          ? {
              connect: args.data.vessel,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CargoManifest)
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "update",
    possession: "any",
  })
  async updateCargoManifest(
    @graphql.Args() args: UpdateCargoManifestArgs
  ): Promise<CargoManifest | null> {
    try {
      return await this.service.updateCargoManifest({
        ...args,
        data: {
          ...args.data,

          vessel: args.data.vessel
            ? {
                connect: args.data.vessel,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CargoManifest)
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "delete",
    possession: "any",
  })
  async deleteCargoManifest(
    @graphql.Args() args: DeleteCargoManifestArgs
  ): Promise<CargoManifest | null> {
    try {
      return await this.service.deleteCargoManifest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Vessel, {
    nullable: true,
    name: "vessel",
  })
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "read",
    possession: "any",
  })
  async getVessel(
    @graphql.Parent() parent: CargoManifest
  ): Promise<Vessel | null> {
    const result = await this.service.getVessel(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
