/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CargoManifestService } from "../cargoManifest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CargoManifestCreateInput } from "./CargoManifestCreateInput";
import { CargoManifest } from "./CargoManifest";
import { CargoManifestFindManyArgs } from "./CargoManifestFindManyArgs";
import { CargoManifestWhereUniqueInput } from "./CargoManifestWhereUniqueInput";
import { CargoManifestUpdateInput } from "./CargoManifestUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CargoManifestControllerBase {
  constructor(
    protected readonly service: CargoManifestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CargoManifest })
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCargoManifest(
    @common.Body() data: CargoManifestCreateInput
  ): Promise<CargoManifest> {
    return await this.service.createCargoManifest({
      data: {
        ...data,

        vessel: data.vessel
          ? {
              connect: data.vessel,
            }
          : undefined,
      },
      select: {
        cargoDescription: true,
        cargoType: true,
        createdAt: true,
        id: true,
        manifestNumber: true,
        portOfDischarge: true,
        portOfLoading: true,
        totalWeight: true,
        updatedAt: true,

        vessel: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CargoManifest] })
  @ApiNestedQuery(CargoManifestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cargoManifests(
    @common.Req() request: Request
  ): Promise<CargoManifest[]> {
    const args = plainToClass(CargoManifestFindManyArgs, request.query);
    return this.service.cargoManifests({
      ...args,
      select: {
        cargoDescription: true,
        cargoType: true,
        createdAt: true,
        id: true,
        manifestNumber: true,
        portOfDischarge: true,
        portOfLoading: true,
        totalWeight: true,
        updatedAt: true,

        vessel: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CargoManifest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cargoManifest(
    @common.Param() params: CargoManifestWhereUniqueInput
  ): Promise<CargoManifest | null> {
    const result = await this.service.cargoManifest({
      where: params,
      select: {
        cargoDescription: true,
        cargoType: true,
        createdAt: true,
        id: true,
        manifestNumber: true,
        portOfDischarge: true,
        portOfLoading: true,
        totalWeight: true,
        updatedAt: true,

        vessel: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CargoManifest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCargoManifest(
    @common.Param() params: CargoManifestWhereUniqueInput,
    @common.Body() data: CargoManifestUpdateInput
  ): Promise<CargoManifest | null> {
    try {
      return await this.service.updateCargoManifest({
        where: params,
        data: {
          ...data,

          vessel: data.vessel
            ? {
                connect: data.vessel,
              }
            : undefined,
        },
        select: {
          cargoDescription: true,
          cargoType: true,
          createdAt: true,
          id: true,
          manifestNumber: true,
          portOfDischarge: true,
          portOfLoading: true,
          totalWeight: true,
          updatedAt: true,

          vessel: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CargoManifest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCargoManifest(
    @common.Param() params: CargoManifestWhereUniqueInput
  ): Promise<CargoManifest | null> {
    try {
      return await this.service.deleteCargoManifest({
        where: params,
        select: {
          cargoDescription: true,
          cargoType: true,
          createdAt: true,
          id: true,
          manifestNumber: true,
          portOfDischarge: true,
          portOfLoading: true,
          totalWeight: true,
          updatedAt: true,

          vessel: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
