/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CargoManifest as PrismaCargoManifest,
  Vessel as PrismaVessel,
} from "@prisma/client";

export class CargoManifestServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CargoManifestCountArgs, "select">
  ): Promise<number> {
    return this.prisma.cargoManifest.count(args);
  }

  async cargoManifests(
    args: Prisma.CargoManifestFindManyArgs
  ): Promise<PrismaCargoManifest[]> {
    return this.prisma.cargoManifest.findMany(args);
  }
  async cargoManifest(
    args: Prisma.CargoManifestFindUniqueArgs
  ): Promise<PrismaCargoManifest | null> {
    return this.prisma.cargoManifest.findUnique(args);
  }
  async createCargoManifest(
    args: Prisma.CargoManifestCreateArgs
  ): Promise<PrismaCargoManifest> {
    return this.prisma.cargoManifest.create(args);
  }
  async updateCargoManifest(
    args: Prisma.CargoManifestUpdateArgs
  ): Promise<PrismaCargoManifest> {
    return this.prisma.cargoManifest.update(args);
  }
  async deleteCargoManifest(
    args: Prisma.CargoManifestDeleteArgs
  ): Promise<PrismaCargoManifest> {
    return this.prisma.cargoManifest.delete(args);
  }

  async getVessel(parentId: string): Promise<PrismaVessel | null> {
    return this.prisma.cargoManifest
      .findUnique({
        where: { id: parentId },
      })
      .vessel();
  }
}
