/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { CargoManifestCreateNestedManyWithoutVesselsInput } from "./CargoManifestCreateNestedManyWithoutVesselsInput";
import { VesselCrewCreateNestedManyWithoutVesselsInput } from "./VesselCrewCreateNestedManyWithoutVesselsInput";

@InputType()
class VesselCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  arrivalTime?: Date | null;

  @ApiProperty({
    required: false,
    type: () => CargoManifestCreateNestedManyWithoutVesselsInput,
  })
  @ValidateNested()
  @Type(() => CargoManifestCreateNestedManyWithoutVesselsInput)
  @IsOptional()
  @Field(() => CargoManifestCreateNestedManyWithoutVesselsInput, {
    nullable: true,
  })
  cargoManifests?: CargoManifestCreateNestedManyWithoutVesselsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  departureTime?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  destinationPort?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nationality?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  portOfOrigin?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeField?: string | null;

  @ApiProperty({
    required: false,
    type: () => VesselCrewCreateNestedManyWithoutVesselsInput,
  })
  @ValidateNested()
  @Type(() => VesselCrewCreateNestedManyWithoutVesselsInput)
  @IsOptional()
  @Field(() => VesselCrewCreateNestedManyWithoutVesselsInput, {
    nullable: true,
  })
  vesselCrews?: VesselCrewCreateNestedManyWithoutVesselsInput;
}

export { VesselCreateInput as VesselCreateInput };
