/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Vessel } from "./Vessel";
import { VesselCountArgs } from "./VesselCountArgs";
import { VesselFindManyArgs } from "./VesselFindManyArgs";
import { VesselFindUniqueArgs } from "./VesselFindUniqueArgs";
import { CreateVesselArgs } from "./CreateVesselArgs";
import { UpdateVesselArgs } from "./UpdateVesselArgs";
import { DeleteVesselArgs } from "./DeleteVesselArgs";
import { CargoManifestFindManyArgs } from "../../cargoManifest/base/CargoManifestFindManyArgs";
import { CargoManifest } from "../../cargoManifest/base/CargoManifest";
import { VesselCrewFindManyArgs } from "../../vesselCrew/base/VesselCrewFindManyArgs";
import { VesselCrew } from "../../vesselCrew/base/VesselCrew";
import { VesselService } from "../vessel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Vessel)
export class VesselResolverBase {
  constructor(
    protected readonly service: VesselService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "read",
    possession: "any",
  })
  async _vesselsMeta(
    @graphql.Args() args: VesselCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Vessel])
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "read",
    possession: "any",
  })
  async vessels(@graphql.Args() args: VesselFindManyArgs): Promise<Vessel[]> {
    return this.service.vessels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Vessel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "read",
    possession: "own",
  })
  async vessel(
    @graphql.Args() args: VesselFindUniqueArgs
  ): Promise<Vessel | null> {
    const result = await this.service.vessel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Vessel)
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "create",
    possession: "any",
  })
  async createVessel(@graphql.Args() args: CreateVesselArgs): Promise<Vessel> {
    return await this.service.createVessel({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Vessel)
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "update",
    possession: "any",
  })
  async updateVessel(
    @graphql.Args() args: UpdateVesselArgs
  ): Promise<Vessel | null> {
    try {
      return await this.service.updateVessel({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Vessel)
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "delete",
    possession: "any",
  })
  async deleteVessel(
    @graphql.Args() args: DeleteVesselArgs
  ): Promise<Vessel | null> {
    try {
      return await this.service.deleteVessel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [CargoManifest], { name: "cargoManifests" })
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "read",
    possession: "any",
  })
  async findCargoManifests(
    @graphql.Parent() parent: Vessel,
    @graphql.Args() args: CargoManifestFindManyArgs
  ): Promise<CargoManifest[]> {
    const results = await this.service.findCargoManifests(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [VesselCrew], { name: "vesselCrews" })
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "read",
    possession: "any",
  })
  async findVesselCrews(
    @graphql.Parent() parent: Vessel,
    @graphql.Args() args: VesselCrewFindManyArgs
  ): Promise<VesselCrew[]> {
    const results = await this.service.findVesselCrews(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
