/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VesselService } from "../vessel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VesselCreateInput } from "./VesselCreateInput";
import { Vessel } from "./Vessel";
import { VesselFindManyArgs } from "./VesselFindManyArgs";
import { VesselWhereUniqueInput } from "./VesselWhereUniqueInput";
import { VesselUpdateInput } from "./VesselUpdateInput";
import { CargoManifestFindManyArgs } from "../../cargoManifest/base/CargoManifestFindManyArgs";
import { CargoManifest } from "../../cargoManifest/base/CargoManifest";
import { CargoManifestWhereUniqueInput } from "../../cargoManifest/base/CargoManifestWhereUniqueInput";
import { VesselCrewFindManyArgs } from "../../vesselCrew/base/VesselCrewFindManyArgs";
import { VesselCrew } from "../../vesselCrew/base/VesselCrew";
import { VesselCrewWhereUniqueInput } from "../../vesselCrew/base/VesselCrewWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VesselControllerBase {
  constructor(
    protected readonly service: VesselService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Vessel })
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVessel(@common.Body() data: VesselCreateInput): Promise<Vessel> {
    return await this.service.createVessel({
      data: data,
      select: {
        arrivalTime: true,
        createdAt: true,
        departureTime: true,
        destinationPort: true,
        id: true,
        name: true,
        nationality: true,
        portOfOrigin: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Vessel] })
  @ApiNestedQuery(VesselFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vessels(@common.Req() request: Request): Promise<Vessel[]> {
    const args = plainToClass(VesselFindManyArgs, request.query);
    return this.service.vessels({
      ...args,
      select: {
        arrivalTime: true,
        createdAt: true,
        departureTime: true,
        destinationPort: true,
        id: true,
        name: true,
        nationality: true,
        portOfOrigin: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Vessel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vessel(
    @common.Param() params: VesselWhereUniqueInput
  ): Promise<Vessel | null> {
    const result = await this.service.vessel({
      where: params,
      select: {
        arrivalTime: true,
        createdAt: true,
        departureTime: true,
        destinationPort: true,
        id: true,
        name: true,
        nationality: true,
        portOfOrigin: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Vessel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVessel(
    @common.Param() params: VesselWhereUniqueInput,
    @common.Body() data: VesselUpdateInput
  ): Promise<Vessel | null> {
    try {
      return await this.service.updateVessel({
        where: params,
        data: data,
        select: {
          arrivalTime: true,
          createdAt: true,
          departureTime: true,
          destinationPort: true,
          id: true,
          name: true,
          nationality: true,
          portOfOrigin: true,
          status: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Vessel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVessel(
    @common.Param() params: VesselWhereUniqueInput
  ): Promise<Vessel | null> {
    try {
      return await this.service.deleteVessel({
        where: params,
        select: {
          arrivalTime: true,
          createdAt: true,
          departureTime: true,
          destinationPort: true,
          id: true,
          name: true,
          nationality: true,
          portOfOrigin: true,
          status: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/cargoManifests")
  @ApiNestedQuery(CargoManifestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CargoManifest",
    action: "read",
    possession: "any",
  })
  async findCargoManifests(
    @common.Req() request: Request,
    @common.Param() params: VesselWhereUniqueInput
  ): Promise<CargoManifest[]> {
    const query = plainToClass(CargoManifestFindManyArgs, request.query);
    const results = await this.service.findCargoManifests(params.id, {
      ...query,
      select: {
        cargoDescription: true,
        cargoType: true,
        createdAt: true,
        id: true,
        manifestNumber: true,
        portOfDischarge: true,
        portOfLoading: true,
        totalWeight: true,
        updatedAt: true,

        vessel: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cargoManifests")
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "update",
    possession: "any",
  })
  async connectCargoManifests(
    @common.Param() params: VesselWhereUniqueInput,
    @common.Body() body: CargoManifestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cargoManifests: {
        connect: body,
      },
    };
    await this.service.updateVessel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cargoManifests")
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "update",
    possession: "any",
  })
  async updateCargoManifests(
    @common.Param() params: VesselWhereUniqueInput,
    @common.Body() body: CargoManifestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cargoManifests: {
        set: body,
      },
    };
    await this.service.updateVessel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cargoManifests")
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "update",
    possession: "any",
  })
  async disconnectCargoManifests(
    @common.Param() params: VesselWhereUniqueInput,
    @common.Body() body: CargoManifestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cargoManifests: {
        disconnect: body,
      },
    };
    await this.service.updateVessel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/vesselCrews")
  @ApiNestedQuery(VesselCrewFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VesselCrew",
    action: "read",
    possession: "any",
  })
  async findVesselCrews(
    @common.Req() request: Request,
    @common.Param() params: VesselWhereUniqueInput
  ): Promise<VesselCrew[]> {
    const query = plainToClass(VesselCrewFindManyArgs, request.query);
    const results = await this.service.findVesselCrews(params.id, {
      ...query,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        nationality: true,
        passportNumber: true,
        role: true,
        updatedAt: true,

        vessel: {
          select: {
            id: true,
          },
        },

        visaStatus: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/vesselCrews")
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "update",
    possession: "any",
  })
  async connectVesselCrews(
    @common.Param() params: VesselWhereUniqueInput,
    @common.Body() body: VesselCrewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vesselCrews: {
        connect: body,
      },
    };
    await this.service.updateVessel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/vesselCrews")
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "update",
    possession: "any",
  })
  async updateVesselCrews(
    @common.Param() params: VesselWhereUniqueInput,
    @common.Body() body: VesselCrewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vesselCrews: {
        set: body,
      },
    };
    await this.service.updateVessel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/vesselCrews")
  @nestAccessControl.UseRoles({
    resource: "Vessel",
    action: "update",
    possession: "any",
  })
  async disconnectVesselCrews(
    @common.Param() params: VesselWhereUniqueInput,
    @common.Body() body: VesselCrewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vesselCrews: {
        disconnect: body,
      },
    };
    await this.service.updateVessel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
